[project]
name = "dagster-xarray"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors=[
    {name="Mike Blackett"}
]
requires-python = ">=3.13,<3.15"
dependencies = [
    "dagster>=1.13.11",
    "pandera[xarray]>=0.32.0",
    "xarray[io,parallel]>=2026.4.0",
]

[build-system]
requires = ["uv_build>=0.9.29,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyterlab>=4.6.0",
    "pyright>=1.1.411",
    "ruff>=0.15.20",
]

[tool.ruff]
line-length = 79

